#!/bin/bash
#
# AST Verifier for SPL compiler
#
# See: https://github.com/X4/CS2103-Tools
# Author: Fernandos
#set -e

rsync -htrpX . _saturn:CS2103
if [ $HOSTNAME != "saturn.mni.fh-giessen.de" ]; then
	ssh _saturn 'bash -c "cd CS2103 && make clean && make verify"'
else
	cd $HOME/CS2103 && make dist-clean && make verify
fi
